theme = 'PaperMod'
baseURL = 'https://sujiantao.github.io/'
locale = 'en-us'
title = 'sujiantao'

[[menu.main]]
    identifier = "about"
    name = "关于"     # 导航栏显示的文字
    url = "/about/"  # 对应 content/about.md
    weight = 30      # 数字越大越靠右
[[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts"
    weight = 10

[[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags"
    weight = 20

[[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about"
    weight = 30